import type { GameBoard } from "./gemini"

// Pre-built game boards for instant gameplay
export const PREBUILT_BOARDS: { [key: string]: GameBoard } = {
  "family-game-night": {
    theme: "Family Game Night",
    storyContext:
      "It's family game night and everyone's gathered around the table. Laughter fills the air as you embark on silly challenges and heartwarming moments together.",
    tiles: [
      {
        id: 0,
        type: "start",
        title: "Game Night Begins",
        description: "Everyone gathers around the table with snacks and excitement!",
        karmaValue: 0,
      },
      {
        id: 1,
        type: "task",
        title: "Memory Lane",
        description: "Share your favorite family memory from this year",
        karmaValue: 5,
      },
      {
        id: 2,
        type: "dare",
        title: "Silly Voice",
        description: "Read the next card in your best cartoon character voice",
        karmaValue: 3,
      },
      {
        id: 3,
        type: "dilemma",
        title: "Snack Sharing",
        description: "There's only one cookie left. What do you do?",
        karmaValue: 0,
        choices: ["Share it with everyone", "Save it for later"],
        consequence: "Your choice shows your generous spirit",
      },
      {
        id: 4,
        type: "action",
        title: "Lucky Roll",
        description: "You found extra dice! Roll again and move 2 extra spaces",
        karmaValue: 2,
      },
      {
        id: 5,
        type: "task",
        title: "Family Trivia",
        description: "Answer a question about another family member correctly",
        karmaValue: 4,
      },
      {
        id: 6,
        type: "bonus",
        title: "Group Hug",
        description: "Everyone gives you a group hug for being awesome!",
        karmaValue: 8,
      },
      {
        id: 7,
        type: "dare",
        title: "Dance Move",
        description: "Teach everyone your signature dance move",
        karmaValue: 3,
      },
      {
        id: 8,
        type: "task",
        title: "Compliment Circle",
        description: "Give a genuine compliment to each family member",
        karmaValue: 6,
      },
      {
        id: 9,
        type: "dilemma",
        title: "Game Choice",
        description: "Someone suggests switching games. Do you agree?",
        karmaValue: 0,
        choices: ["Go with the flow", "Stick to current game"],
        consequence: "Flexibility brings harmony",
      },
      {
        id: 10,
        type: "action",
        title: "Oops!",
        description: "You accidentally knocked over the snack bowl. Help clean up!",
        karmaValue: -1,
      },
      {
        id: 11,
        type: "task",
        title: "Storytelling",
        description: "Tell a funny story about a family pet or adventure",
        karmaValue: 4,
      },
      {
        id: 12,
        type: "dare",
        title: "Impression Time",
        description: "Do your best impression of another family member (lovingly!)",
        karmaValue: 3,
      },
      {
        id: 13,
        type: "bonus",
        title: "MVP Moment",
        description: "You're declared the MVP of family fun time!",
        karmaValue: 6,
      },
      {
        id: 14,
        type: "dilemma",
        title: "Bedtime Call",
        description: "It's getting late but the game is fun. What do you suggest?",
        karmaValue: 0,
        choices: ["One more round", "Save game for tomorrow"],
        consequence: "Wisdom guides your choice",
      },
      {
        id: 15,
        type: "task",
        title: "Gratitude Round",
        description: "Share what you're most grateful for about your family",
        karmaValue: 7,
      },
      {
        id: 16,
        type: "action",
        title: "Photo Op",
        description: "Take a silly family photo to remember this moment",
        karmaValue: 1,
      },
      { id: 17, type: "dare", title: "Talent Show", description: "Show off a hidden talent or skill", karmaValue: 4 },
      {
        id: 18,
        type: "bonus",
        title: "Family Champion",
        description: "You've brought everyone closer together tonight!",
        karmaValue: 5,
      },
      {
        id: 19,
        type: "finish",
        title: "Game Night Victory",
        description: "What a perfect family game night! Everyone wins when family comes together.",
        karmaValue: 10,
      },
    ],
  },

  "office-team-building": {
    theme: "Office Team Building Adventure",
    storyContext:
      "Your team is on a corporate retreat designed to build trust, communication, and camaraderie. Navigate workplace challenges while strengthening professional relationships.",
    tiles: [
      {
        id: 0,
        type: "start",
        title: "Team Retreat Begins",
        description: "Welcome to the company retreat! Time to bond with your colleagues.",
        karmaValue: 0,
      },
      {
        id: 1,
        type: "task",
        title: "Icebreaker Challenge",
        description: "Share an interesting fact about yourself that nobody knows",
        karmaValue: 5,
      },
      {
        id: 2,
        type: "dare",
        title: "Elevator Pitch",
        description: "Give a 30-second pitch for why pineapple belongs on pizza",
        karmaValue: 3,
      },
      {
        id: 3,
        type: "dilemma",
        title: "Coffee Crisis",
        description: "The coffee machine is broken. How do you handle the team's caffeine needs?",
        karmaValue: 0,
        choices: ["Organize a coffee run", "Suggest tea alternatives"],
        consequence: "Leadership emerges in small moments",
      },
      {
        id: 4,
        type: "action",
        title: "Networking Win",
        description: "You make a great connection with someone from another department",
        karmaValue: 2,
      },
      {
        id: 5,
        type: "task",
        title: "Problem Solving",
        description: "Help solve a hypothetical workplace challenge as a team",
        karmaValue: 4,
      },
      {
        id: 6,
        type: "bonus",
        title: "Innovation Award",
        description: "Your creative thinking impresses everyone!",
        karmaValue: 8,
      },
      {
        id: 7,
        type: "dare",
        title: "Presentation Skills",
        description: "Present the weather forecast like you're giving a quarterly report",
        karmaValue: 3,
      },
      {
        id: 8,
        type: "task",
        title: "Collaboration Station",
        description: "Lead a mini brainstorming session on improving office culture",
        karmaValue: 6,
      },
      {
        id: 9,
        type: "dilemma",
        title: "Deadline Pressure",
        description: "A colleague is struggling with their retreat activity. Do you help?",
        karmaValue: 0,
        choices: ["Offer assistance", "Let them figure it out"],
        consequence: "Teamwork makes the dream work",
      },
      {
        id: 10,
        type: "action",
        title: "Tech Trouble",
        description: "The projector isn't working. You volunteer to troubleshoot",
        karmaValue: -1,
      },
      {
        id: 11,
        type: "task",
        title: "Communication Challenge",
        description: "Explain a complex process using only drawings",
        karmaValue: 4,
      },
      {
        id: 12,
        type: "dare",
        title: "Office Talent",
        description: "Demonstrate a skill that would be useful in the office",
        karmaValue: 3,
      },
      {
        id: 13,
        type: "bonus",
        title: "Team Player Award",
        description: "You're recognized for outstanding collaboration!",
        karmaValue: 6,
      },
      {
        id: 14,
        type: "dilemma",
        title: "Feedback Time",
        description: "It's time for peer feedback. How do you approach it?",
        karmaValue: 0,
        choices: ["Give honest, constructive feedback", "Keep it light and positive"],
        consequence: "Growth requires honest communication",
      },
      {
        id: 15,
        type: "task",
        title: "Vision Sharing",
        description: "Share your vision for the team's future success",
        karmaValue: 7,
      },
      {
        id: 16,
        type: "action",
        title: "Lunch Coordination",
        description: "You organize the lunch seating to mix up the usual groups",
        karmaValue: 1,
      },
      {
        id: 17,
        type: "dare",
        title: "Leadership Moment",
        description: "Lead the team in a motivational chant or cheer",
        karmaValue: 4,
      },
      {
        id: 18,
        type: "bonus",
        title: "Culture Champion",
        description: "You've helped create a more positive team dynamic!",
        karmaValue: 5,
      },
      {
        id: 19,
        type: "finish",
        title: "Retreat Success",
        description: "The team building retreat is complete! You've built stronger professional relationships.",
        karmaValue: 10,
      },
    ],
  },

  "college-roommates": {
    theme: "College Roommates Reunion",
    storyContext:
      "You're reuniting with your college roommates for a weekend of nostalgia, inside jokes, and catching up on life. Relive the good times while creating new memories.",
    tiles: [
      {
        id: 0,
        type: "start",
        title: "Reunion Begins",
        description: "The gang's all here! Time to catch up and relive the college days.",
        karmaValue: 0,
      },
      {
        id: 1,
        type: "task",
        title: "Memory Match",
        description: "Correctly guess which roommate did something embarrassing in college",
        karmaValue: 5,
      },
      {
        id: 2,
        type: "dare",
        title: "Dorm Room Dance",
        description: "Recreate your signature move from college parties",
        karmaValue: 3,
      },
      {
        id: 3,
        type: "dilemma",
        title: "Pizza Debate",
        description: "You can't agree on pizza toppings. How do you resolve this?",
        karmaValue: 0,
        choices: ["Compromise with half and half", "Order multiple pizzas"],
        consequence: "Diplomacy learned from years of shared living",
      },
      {
        id: 4,
        type: "action",
        title: "Photo Discovery",
        description: "You find hilarious old photos on your phone to share",
        karmaValue: 2,
      },
      {
        id: 5,
        type: "task",
        title: "Professor Impression",
        description: "Do your best impression of your most memorable professor",
        karmaValue: 4,
      },
      {
        id: 6,
        type: "bonus",
        title: "Nostalgia Trip",
        description: "You perfectly recreate an inside joke that has everyone in stitches!",
        karmaValue: 8,
      },
      {
        id: 7,
        type: "dare",
        title: "Karaoke Throwback",
        description: "Sing the song you all used to blast in the dorm",
        karmaValue: 3,
      },
      {
        id: 8,
        type: "task",
        title: "Life Updates",
        description: "Give an honest update about your life since graduation",
        karmaValue: 6,
      },
      {
        id: 9,
        type: "dilemma",
        title: "Party Planning",
        description: "Someone suggests going out vs. staying in. What's your vote?",
        karmaValue: 0,
        choices: ["Adventure awaits outside", "Cozy night in together"],
        consequence: "The best times are with good friends",
      },
      {
        id: 10,
        type: "action",
        title: "Spill Alert",
        description: "You accidentally spill something, just like old times!",
        karmaValue: -1,
      },
      {
        id: 11,
        type: "task",
        title: "Advice Corner",
        description: "Give advice to a roommate about a current life challenge",
        karmaValue: 4,
      },
      {
        id: 12,
        type: "dare",
        title: "Fashion Flashback",
        description: "Describe your worst college outfit in dramatic detail",
        karmaValue: 3,
      },
      {
        id: 13,
        type: "bonus",
        title: "Friendship Goals",
        description: "You're voted 'Most Likely to Keep Everyone Together'",
        karmaValue: 6,
      },
      {
        id: 14,
        type: "dilemma",
        title: "Secret Sharing",
        description: "Someone wants to share a college secret. How do you respond?",
        karmaValue: 0,
        choices: ["Encourage openness", "Respect their privacy"],
        consequence: "Trust is the foundation of lasting friendship",
      },
      {
        id: 15,
        type: "task",
        title: "Future Plans",
        description: "Plan the next roommate reunion together",
        karmaValue: 7,
      },
      {
        id: 16,
        type: "action",
        title: "Group Selfie",
        description: "Organize the perfect group photo for social media",
        karmaValue: 1,
      },
      {
        id: 17,
        type: "dare",
        title: "Toast Master",
        description: "Give a heartfelt toast to your college friendships",
        karmaValue: 4,
      },
      {
        id: 18,
        type: "bonus",
        title: "Reunion MVP",
        description: "You've made this the best reunion yet!",
        karmaValue: 5,
      },
      {
        id: 19,
        type: "finish",
        title: "Friends Forever",
        description: "Another amazing reunion in the books! College friends are friends for life.",
        karmaValue: 10,
      },
    ],
  },

  "sibling-adventure": {
    theme: "Sibling Adventure Day",
    storyContext:
      "You and your siblings are spending quality time together, navigating the unique dynamics of family bonds, childhood memories, and the love-hate relationship only siblings understand.",
    tiles: [
      {
        id: 0,
        type: "start",
        title: "Sibling Time",
        description: "Just you and your siblings - let the chaos and love begin!",
        karmaValue: 0,
      },
      {
        id: 1,
        type: "task",
        title: "Childhood Memory",
        description: "Share your favorite memory of playing together as kids",
        karmaValue: 5,
      },
      {
        id: 2,
        type: "dare",
        title: "Sibling Rivalry",
        description: "Challenge a sibling to your childhood competition (arm wrestling, staring contest, etc.)",
        karmaValue: 3,
      },
      {
        id: 3,
        type: "dilemma",
        title: "Old Arguments",
        description: "Someone brings up an old sibling fight. How do you handle it?",
        karmaValue: 0,
        choices: ["Laugh it off", "Settle it once and for all"],
        consequence: "Time heals old wounds",
      },
      {
        id: 4,
        type: "action",
        title: "Inside Joke",
        description: "You reference a family inside joke that only siblings would understand",
        karmaValue: 2,
      },
      {
        id: 5,
        type: "task",
        title: "Parent Impression",
        description: "Do your best impression of Mom or Dad when they were mad",
        karmaValue: 4,
      },
      {
        id: 6,
        type: "bonus",
        title: "Sibling Telepathy",
        description: "You and a sibling say the exact same thing at the same time!",
        karmaValue: 8,
      },
      {
        id: 7,
        type: "dare",
        title: "Embarrassing Story",
        description: "Tell an embarrassing story about another sibling (with love!)",
        karmaValue: 3,
      },
      {
        id: 8,
        type: "task",
        title: "Protective Instinct",
        description: "Share a time when you stood up for a sibling",
        karmaValue: 6,
      },
      {
        id: 9,
        type: "dilemma",
        title: "Favorite Child",
        description: "The topic of who's the favorite comes up. How do you respond?",
        karmaValue: 0,
        choices: ["Joke about it", "Change the subject"],
        consequence: "Every sibling is special in their own way",
      },
      {
        id: 10,
        type: "action",
        title: "Sibling Squabble",
        description: "A minor disagreement breaks out over something silly",
        karmaValue: -1,
      },
      {
        id: 11,
        type: "task",
        title: "Advice Exchange",
        description: "Give genuine advice to a sibling about something they're dealing with",
        karmaValue: 4,
      },
      {
        id: 12,
        type: "dare",
        title: "Talent Comparison",
        description: "Show off a skill and challenge siblings to do better",
        karmaValue: 3,
      },
      {
        id: 13,
        type: "bonus",
        title: "Sibling Support",
        description: "You're there for a sibling when they need you most",
        karmaValue: 6,
      },
      {
        id: 14,
        type: "dilemma",
        title: "Family Secrets",
        description: "Someone mentions something you weren't supposed to tell parents. What now?",
        karmaValue: 0,
        choices: ["Keep the secret", "Come clean together"],
        consequence: "Sibling loyalty runs deep",
      },
      {
        id: 15,
        type: "task",
        title: "Future Dreams",
        description: "Share your hopes for your sibling relationships as you all grow older",
        karmaValue: 7,
      },
      {
        id: 16,
        type: "action",
        title: "Photo Hunt",
        description: "Look through old family photos and laugh at your younger selves",
        karmaValue: 1,
      },
      {
        id: 17,
        type: "dare",
        title: "Appreciation Speech",
        description: "Give a sincere speech about what each sibling means to you",
        karmaValue: 4,
      },
      {
        id: 18,
        type: "bonus",
        title: "Sibling Bond",
        description: "You've strengthened the unbreakable sibling connection!",
        karmaValue: 5,
      },
      {
        id: 19,
        type: "finish",
        title: "Family Forever",
        description: "No matter what, siblings stick together. Another great day in the books!",
        karmaValue: 10,
      },
    ],
  },

  "friends-night-out": {
    theme: "Friends Night Out",
    storyContext:
      "You and your best friends are having an epic night out on the town. Navigate social situations, make memories, and strengthen friendships through shared adventures.",
    tiles: [
      {
        id: 0,
        type: "start",
        title: "Night Out Begins",
        description: "The squad is assembled and ready for an unforgettable night!",
        karmaValue: 0,
      },
      {
        id: 1,
        type: "task",
        title: "Group Decision",
        description: "Successfully get everyone to agree on where to go first",
        karmaValue: 5,
      },
      {
        id: 2,
        type: "dare",
        title: "Confidence Boost",
        description: "Hype up a friend who's feeling nervous about something",
        karmaValue: 3,
      },
      {
        id: 3,
        type: "dilemma",
        title: "Budget Conscious",
        description: "Someone's running low on money. How does the group handle it?",
        karmaValue: 0,
        choices: ["Pool money to help", "Find free activities"],
        consequence: "True friends support each other",
      },
      {
        id: 4,
        type: "action",
        title: "Social Butterfly",
        description: "You make new friends while you're out and introduce them to the group",
        karmaValue: 2,
      },
      {
        id: 5,
        type: "task",
        title: "Wing Person",
        description: "Help a friend start a conversation with someone they find interesting",
        karmaValue: 4,
      },
      {
        id: 6,
        type: "bonus",
        title: "Squad Goals",
        description: "Your group becomes the life of the party wherever you go!",
        karmaValue: 8,
      },
      {
        id: 7,
        type: "dare",
        title: "Karaoke Star",
        description: "Convince the group to do karaoke and lead by example",
        karmaValue: 3,
      },
      {
        id: 8,
        type: "task",
        title: "Designated Helper",
        description: "Take care of a friend who's had a bit too much fun",
        karmaValue: 6,
      },
      {
        id: 9,
        type: "dilemma",
        title: "Drama Alert",
        description: "There's some tension between two friends. Do you intervene?",
        karmaValue: 0,
        choices: ["Mediate the situation", "Let them work it out"],
        consequence: "Sometimes friendship requires tough choices",
      },
      {
        id: 10,
        type: "action",
        title: "Oops Moment",
        description: "You accidentally embarrass yourself but laugh it off",
        karmaValue: -1,
      },
      {
        id: 11,
        type: "task",
        title: "Memory Maker",
        description: "Organize a group photo or activity that everyone will remember",
        karmaValue: 4,
      },
      {
        id: 12,
        type: "dare",
        title: "Dance Floor",
        description: "Get everyone dancing, even the shy ones",
        karmaValue: 3,
      },
      {
        id: 13,
        type: "bonus",
        title: "Friend of the Year",
        description: "You're voted the best friend in the group tonight!",
        karmaValue: 6,
      },
      {
        id: 14,
        type: "dilemma",
        title: "Late Night Decision",
        description: "It's getting late. Do you call it a night or keep the party going?",
        karmaValue: 0,
        choices: ["One more spot", "End on a high note"],
        consequence: "Knowing when to stop is wisdom",
      },
      {
        id: 15,
        type: "task",
        title: "Heart to Heart",
        description: "Have a meaningful conversation with a friend about life",
        karmaValue: 7,
      },
      {
        id: 16,
        type: "action",
        title: "Safety First",
        description: "Make sure everyone gets home safely",
        karmaValue: 1,
      },
      {
        id: 17,
        type: "dare",
        title: "Gratitude Round",
        description: "Tell each friend why you're grateful for them",
        karmaValue: 4,
      },
      {
        id: 18,
        type: "bonus",
        title: "Epic Night",
        description: "You've created memories that will last a lifetime!",
        karmaValue: 5,
      },
      {
        id: 19,
        type: "finish",
        title: "Friends Forever",
        description: "What an amazing night with amazing friends! These are the moments you'll treasure forever.",
        karmaValue: 10,
      },
    ],
  },
}

// Quick theme suggestions for the home page
export const QUICK_THEMES = [
  "Family Game Night",
  "Office Team Building Adventure",
  "College Roommates Reunion",
  "Sibling Adventure Day",
  "Friends Night Out",
]

// Function to get a prebuilt board by theme
export function getPrebuiltBoard(theme: string): GameBoard | null {
  const key = theme.toLowerCase().replace(/\s+/g, "-")
  return PREBUILT_BOARDS[key] || null
}

// Function to check if a theme has a prebuilt board
export function hasPrebuiltBoard(theme: string): boolean {
  const key = theme.toLowerCase().replace(/\s+/g, "-")
  return key in PREBUILT_BOARDS
}

// Function to get all available prebuilt themes
export function getAvailableThemes(): string[] {
  return Object.values(PREBUILT_BOARDS).map((board) => board.theme)
}
